### ISSUE TITLE
Base32 decoder should ignore the case

### ISSUE THREAD

**Issue by Stebalien** [multiformats/go-multibase#16]
It currently doesn't accept lower case :(.

**Comment by kevina** [comment]
I agree, looking into it now.

**Comment by kevina** [comment]
Once https://github.com/whyrusleeping/base32/pull/3 gets merged and the dependency updated this should be fixed, although there are some other things I don't like regarding how case is handled, but at least it will accept lower case.

**Comment by kevina** [comment]
The dependency needs to be updated.

**Comment by kevina** [comment]
Fixed Now.
